### PR TITLE
Purge slog for more ergonomic usage

### PR DESCRIPTION
**Pull request by Yatekii**
I removed slog from the crate to make usage more ergonomic and similar to what other crates do mostly.

There is no real replacement for the kv-replacement feature of slog. I tried my best to keep the information logged as before, but surely it wount be 100% the same.

Also, I used simplelog, which should generate nice, colored terminal output.

If anything is unsound, please point me to it, I'll hapily fix it.

### CODE REVIEW

**Comment by theotherjimmy** [comment]
> There is no real replacement for the kv-replacement feature of slog. I tried my best to keep the information logged as before, but surely it wount be 100% the same.

That's great! I'm not worried about this log output changing from release to release, so long as users get something that we can handle in issues.

**Comment by Yatekii** [comment]
Yep, the CI fails for the same reason the previous PR does. I am gonna try and fix this. I already tried but I have no clue yet :/

**Comment by theotherjimmy** [comment]
I appreciate your efforts. You can find the CI scripts in this repo if that helps.

**Comment by mathias-arm** [comment]
This was folded into #143

**Pull request closed without merging**
