### PR TITLE
Fix clippy lints

### PR DESCRIPTION
**Pull request by Yatekii**
I fixed all the clipply lints.

Somehow now cbindgen doesn't generate bindings for many of the extern "C" functions.
Also, `python2 setup.py bdist_wheel` as stated in the readme does not work at all. It tells me that bdist_wheel is no valid command.

Maybe you can have a look and help me get this right (I fix it myself, I just need a hint)

### CODE REVIEW

**Comment by theotherjimmy** [comment]
For the `bdist_wheel` subcommand, I think you need to have the python `wheel` package installed before invoking that command line.

**Comment by theotherjimmy** [comment]
I like naming the unified crate `cmsis-pack` that seems reasonable to me. This looks like it is based on #134 So I'll be sure to merge that first.

**Comment by theotherjimmy** [comment]
The errors in CI indicate that something has gone wrong on the python side of things, which you did not touch. The extra weird bit is that your other 2 PRs, which you submitted at a similar time, both passed.

**Comment by Yatekii** [comment]
Ok, I will try some more and try to run the python side of things too. Something with cffi seems to be odd (it removed many function signatures from the generated headerfile). I didn't figure yet what it is :/

**Comment by mathias-arm** [comment]
This was folded into #143

**Pull request closed without merging**
