### PR TITLE
Updated dependencies.

### PR DESCRIPTION
**Pull request by Sup3rGeo**
Fixes https://github.com/ARMmbed/cmsis-pack-manager/issues/139, based on probe-rs/target-gen#9

### CODE REVIEW

**Comment by Sup3rGeo** [comment]
@theotherjimmy when is the next release expected?

**Comment by theotherjimmy** [comment]
Hi @Sup3rGeo, that's a question for @flit , as I no longer release or maintain this package.

**Comment by flit** [comment]
@Sup3rGeo Version 0.2.10 was just released.

**Comment by Sup3rGeo** [comment]
@flit thanks! Could you also upload the tar.gz source package as done in the previous releases as well? This is the one used by the raspberry pi when pip installing it

**Comment by flit** [comment]
Certainly, sorry!

**Comment by flit** [comment]
@Sup3rGeo Source tarball is uploaded now, sorry it took a while.

**Comment by Sup3rGeo** [comment]
@flit great, thank you!

**Pull request merged**
